# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="$PYENV_ROOT/bin:$PATH"
. "$HOME/.cargo/env"

export VIRTUAL_ENV=~/.virtualenvs
export PYENV_ROOT=$VIRTUAL_ENV
export WORKON_HOME=$VIRTUAL_ENV
export POETRY_VIRTUALENVS_PATH=$VIRTUAL_ENV
