

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export VIRTUAL_ENV=~/.virtualenvs

# PYTHON specific settings
export WORKON_HOME=$VIRTUAL_ENV
export POETRY_VIRTUALENVS_PATH=$VIRTUAL_ENV